<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <ProjectReference Include="..\WardrobeManager.Domain\WardrobeManager.Domain.csproj" />
    </ItemGroup>

</Project>
