<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WardrobeManager.Application\WardrobeManager.Application.csproj" />
      <ProjectReference Include="..\WardrobeManager.Infrastructure\WardrobeManager.Infrastructure.csproj" />
    </ItemGroup>

</Project>
