import COLOR_GROUPS_RAW from './colors.json';

// Color taxonomy — single source of truth. `colors.json` is generated by
// `scripts/fetch_colors.py` from the meodai color dataset and shared with the ML
// service (ml_api/colors.json). Shape: { main: { hex, shades: { name: hex } } }.
export const COLOR_GROUPS = COLOR_GROUPS_RAW;

// Flat name → hex map (every main color and shade). Drives swatch resolution and the
// dropdown order; main colors are single words so they also serve as word-level fallbacks.
export const COLOR_HEX = Object.fromEntries(
  Object.entries(COLOR_GROUPS).flatMap(
    ([main, group]) => [[main, group.hex], ...Object.entries(group.shades)]
  )
);

// True if `value` is a CSS-recognized color keyword (browser only).
function isCssColor(value) {
  if (typeof document === 'undefined') return false;
  const probe = new Option().style;
  probe.color = '';
  probe.color = value;
  return probe.color !== '';
}

/**
 * Resolve any color name to a hex/CSS color, or null when unknown.
 * Order: exact taxonomy match → most-specific word in the taxonomy → CSS keyword → null.
 * A null return means the caller should render a neutral placeholder, never "nothing".
 */
export function colorToHex(name) {
  if (!name) return null;
  const key = String(name).toLowerCase().trim().replace(/\s+/g, ' ');
  if (!key) return null;

  // 1. Exact taxonomy match — covers every name the ML can produce.
  if (COLOR_HEX[key]) return COLOR_HEX[key];

  // 2. Word fallback: check the most specific (last) word first, so "emerald green"
  //    falls back to "green" and "dark teal" to "teal".
  const words = key.split(' ');
  for (let i = words.length - 1; i >= 0; i--) {
    if (COLOR_HEX[words[i]]) return COLOR_HEX[words[i]];
  }

  // 3. A plain CSS keyword the browser understands (e.g. "navy", "tomato").
  if (isCssColor(key)) return key;

  // 4. Unknown — caller renders a neutral placeholder.
  return null;
}
